[package]
name = "devtool"
version = "0.2.0"
edition = "2021"
description = "A CLI tool for development in update rustup toolchain , mise maintained tools and hombrew packages."
repository = "https://github.com/jenkinpan/devtool-rs"
license = "MIT OR Apache-2.0"
keywords = ["cli", "development", "rust"]

[dependencies]
anyhow = "1"
atty = "0.2"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
dirs = "6"
regex = "1"
# Using serde for status JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
which = "8"
