name: Test Homebrew Push

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: jenkinpan/homebrew-tap
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TAP_DEPLOY_KEY }}

      - name: Test Git Configuration
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Configure Git to use SSH for GitHub
          git config --local url."git@github.com:".insteadOf "https://github.com/"
          
          echo "Current branch: $(git branch --show-current)"
          echo "Remote branches:"
          git branch -r
          echo "Remote info:"
          git remote -v

      - name: Test Push
        run: |
          cd homebrew-tap
          # Create a test file
          echo "# Test push $(date)" >> test-push.txt
          git add test-push.txt
          git commit -m "test: verify SSH push capability" || echo "No changes to commit"
          
          echo "Attempting to push to master using SSH..."
          if git push origin master; then
            echo "✅ Successfully pushed to master using SSH"
          else
            echo "❌ Failed to push to master"
            echo "Git status:"
            git status
            echo "Git log:"
            git log --oneline -5
            echo "Remote info:"
            git remote -v
            exit 1
          fi
